### ISSUE TITLE
Train BUG

### ISSUE THREAD

**Issue by DezhiKong00** [Lornatang/Real_ESRGAN-PyTorch#12]
I am getting the following bug when loading.

Traceback (most recent call last):
  File "D:\KDZ\Real_ESRGAN-blind-self\train_realesrnet.py", line 327, in <module>
    main()
  File "D:\KDZ\Real_ESRGAN-blind-self\train_realesrnet.py", line 40, in main
    degenerated_train_prefetcher, paired_test_prefetcher = load_dataset()
  File "D:\KDZ\Real_ESRGAN-blind-self\train_realesrnet.py", line 159, in load_dataset
    degenerated_train_prefetcher = CUDAPrefetcher(degenerated_train_dataloader, realesrnet_config.device)
  File "D:\KDZ\Real_ESRGAN-blind-self\dataset.py", line 279, in __init__
    self.preload()
  File "D:\KDZ\Real_ESRGAN-blind-self\dataset.py", line 283, in preload
    self.batch_data = next(self.data)
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\utils\data\_utils\collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\utils\data\_utils\collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "C:\ProgramData\Anaconda3\envs\kdzenv\lib\site-packages\torch\utils\data\_utils\collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 1356, 2040] at entry 0 and [3, 1284, 2040] at entry 1

进程已结束,退出代码1

**Comment by DezhiKong00** [comment]
大佬，急需您解决这个问题，数据处理过程太复杂了，我找不到BUG所在地方。

**Comment by DezhiKong00** [comment]
我仔细看了一下您的代码，我觉得是因为您的输入图像大小不同导致的，之前训练您的ESRGAN，是再在dataload时就已经将图像进行了裁剪，所以放到一个btach的时候是相同大小的，不会报错，而这里是保存了原始图像大小。

**Comment by Lornatang** [comment]
现在这部分已经全部统一尺寸了
