### ISSUE TITLE
NIQE计算时除数为0

### ISSUE THREAD

**Issue by Wakie01** [Lornatang/Real_ESRGAN-PyTorch#5]
大佬，我在评估General100数据集时，碰到了这个问题：在计算NIQE时出现了除数为0，你说会不会是精度问题，自动简化为0
```
Traceback (most recent call last):
  File "test.py", line 115, in <module>
    main()
  File "test.py", line 99, in main
    niqe_metrics += niqe(sr_tensor).item()
  File "/home/wakie/anaconda3/envs/esrgan_tang/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wakie/python_works/Second_Half/Real_ESRGAN-PyTorch/image_quality_assessment.py", line 1027, in forward
    niqe_metrics = _niqe_torch(raw_tensor,
  File "/home/wakie/python_works/Second_Half/Real_ESRGAN-PyTorch/image_quality_assessment.py", line 993, in _niqe_torch
    niqe_metric = _fit_mscn_ipac_torch(y_tensor,
  File "/home/wakie/python_works/Second_Half/Real_ESRGAN-PyTorch/image_quality_assessment.py", line 941, in _fit_mscn_ipac_torch
    cov_distparam = _nancov_torch(distparam)
  File "/home/wakie/python_works/Second_Half/Real_ESRGAN-PyTorch/image_quality_assessment.py", line 638, in _nancov_torch
    cov_x = _cov_torch(x_no_nan, rowvar=False)
  File "/home/wakie/python_works/Second_Half/Real_ESRGAN-PyTorch/image_quality_assessment.py", line 622, in _cov_torch
    factor = 1 / (tensor.shape[-1] - int(not bool(bias)))
ZeroDivisionError: division by zero
```

**Comment by Lornatang** [comment]
有可能，你尝试加一个eps试试？

**Comment by Wakie01** [comment]
不知道怎么改呢？

**Comment by Lornatang** [comment]
已修复上述问题。

刚尝试打印公式中的变量，是特征维度不足导致，设定一个阈值即可，而且不会对其它结果造成任何影响

**Comment by Wakie01** [comment]
好的，谢谢大佬
