### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ilie321** [Lornatang/Real_ESRGAN-PyTorch#9]
hello any idee why i get this?
Traceback (most recent call last):
  File "D:\ttt\train_realesrgan.py", line 472, in <module>
    main()
  File "D:\ttt\train_realesrgan.py", line 114, in main
    train(d_model,
  File "D:\ttt\train_realesrgan.py", line 354, in train
    gt_usm, gt, lr = imgproc.degradation_process(gt,
  File "D:\ttt\imgproc.py", line 2359, in degradation_process
    gt_usm = usm_sharpener(gt)
  File "C:\Users\ilie3\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: USMSharp.forward() missing 2 required positional arguments: 'weight' and 'threshold'

**Comment by ilie321** [comment]
or this Traceback (most recent call last):
  File "D:\ttt\train_realesrgan.py", line 472, in <module>
    main()
  File "D:\ttt\train_realesrgan.py", line 128, in main
    niqe = validate(g_model,
  File "D:\ttt\utils.py", line 147, in validate
    niqe = niqe_model(sr, gt)
  File "C:\Users\ilie3\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: NIQE.forward() takes 2 positional arguments but 3 were given

**Comment by ilie321** [comment]
what i do wrong?

**Comment by Lornatang** [comment]
Thank you for pointing out this problem, this error should be that the code is out of sync
